sudo: required

language: go

go:
  - tip

services:
  - docker

cache:
  - apt

before_install:
  #- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  #- docker build -t itsbalamurali/heyasha .
  #- docker push itsbalamurali/heyasha

install:
  - go get -u github.com/kardianos/govendor
  - govendor sync
notifications:
  slack: heyasha:m1OwwwmiydtXPLKeUY1jwGzd
  email: false