sudo: required

language: go

go:
  - tip

#services:
#  - docker

#before_install:
#  - docker build -t itsbalamurali/heyasha .

install:
  - go get -u github.com/kardianos/govendor
  - govendor sync
