#Environment Dev/Prod?
environment = "dev"

#Database Settings
[database]
	#Mongodb Settings
	[database.mongodb]
	dbhost = ""
	dbport = 27017
	dbuser = ""
	dbname = ""
	dbpassword = ""
	#MySql Settings
	[database.mysql]
	dbhost = ""
	dbport = 3306
	dbuser = ""
	dbname = ""
	dbpassword = ""
#SMTP email settings
[email]

#SMS settings
[sms]

#Google Cloud Bucket
[google_cloud]
	[google_cloud.storage]
	bucket_name = ""

#PocketSphinx Settings	
[pocketsphinx]
	#Language models
    [pocketsphinx.en]
        hmm= "data/stt/models/en-us/en-us"
        dic= "data/stt/models/en-us/cmudict-en-us.dict"
        disableinfo = false
        #kws= "path_to_kws"
        #kws_threshold= "1e-60"
        #kws_plp= "1e-60"
