#Environment Dev/Prod?
environment = "dev"
#Database Settings
#SMTP email settings
[email]

#Mongodb Settings
mongo_uri = "mongodb://murali:yourass1994@ds011872.mlab.com:11872/heyasha"
mysql_uri = "mysql://admin_twa:Aydim4VdBK@128.199.81.183:3306/admin_twa"

#SMS settings
[sms]

#Google Cloud Bucket
google_cloud_bucket = ""